export const appContent = {
  appName: "Camino",
  tagline: "Planificá tu día, tu semana y tus objetivos",
  nav: {
    dashboard: "Hoy",
    weekly: "Semana",
    monthlyGoals: "Objetivos mensuales",
    annualGoals: "Objetivos anuales",
    football: "Fútbol",
  },
  auth: {
    loginTitle: "Iniciar sesión",
    registerTitle: "Crear cuenta",
    email: "Correo electrónico",
    password: "Contraseña",
    name: "Nombre",
    loginButton: "Ingresar",
    registerButton: "Registrarse",
    googleButton: "Continuar con Google",
    noAccount: "¿No tenés cuenta?",
    hasAccount: "¿Ya tenés cuenta?",
    registerLink: "Registrate",
    loginLink: "Iniciá sesión",
    logout: "Cerrar sesión",
    errors: {
      invalidCredentials: "Correo o contraseña incorrectos",
      emailInUse: "Este correo ya está registrado",
      googleConflict: "Este correo ya tiene cuenta con contraseña. Iniciá sesión con email.",
      dbUnavailable: "No se pudo conectar a la base de datos. Revisá tu conexión o la configuración de Atlas.",
      generic: "Ocurrió un error. Intentá de nuevo.",
    },
  },
  dashboard: {
    title: "Agenda de hoy",
    subtitle: "Tareas organizadas por bloque horario",
    emptySlot: "Escribí una tarea…",
    addTask: "Agregar tarea",
    editTask: "Editar tarea",
    markComplete: "Completar",
    markIncomplete: "Marcar pendiente",
    deleteTask: "Eliminar",
    taskTitle: "Tarea",
    save: "Guardar",
    cancel: "Cancelar",
    completed: "Completada",
    pending: "Pendiente",
  },
  weekly: {
    title: "Planificación semanal",
    subtitle: "Agenda y objetivos de la semana",
    agendaTitle: "Agenda semanal",
    goalsTitle: "Objetivos semanales",
    prevWeek: "Semana anterior",
    nextWeek: "Semana siguiente",
    addGoal: "Nuevo objetivo",
    goalPlaceholder: "Escribí un objetivo para esta semana",
  },
  monthlyGoals: {
    title: "Objetivos mensuales",
    subtitle: "Metas del mes en curso",
    addGoal: "Nuevo objetivo",
    goalPlaceholder: "Objetivo del mes",
    prevMonth: "Mes anterior",
    nextMonth: "Mes siguiente",
  },
  annualGoals: {
    title: "Objetivos anuales",
    subtitle: "Metas del año",
    addGoal: "Nuevo objetivo",
    goalPlaceholder: "Objetivo del año",
    prevYear: "Año anterior",
    nextYear: "Año siguiente",
  },
  goals: {
    markComplete: "Completar",
    markIncomplete: "Marcar pendiente",
    edit: "Editar",
    delete: "Eliminar",
    empty: "No hay objetivos todavía",
    save: "Guardar",
    cancel: "Cancelar",
  },
  football: {
    title: "Fútbol",
    subtitle: "Buscá partidos por fecha, liga o equipo",
    date: "Fecha",
    league: "Liga",
    anyLeague: "Todas las ligas",
    team: "Equipo",
    teamPlaceholder: "Ej. Arsenal",
    clearTeam: "Quitar",
    scope: "Para liga/equipo",
    scopeNext: "Próximos",
    scopeLast: "Últimos",
    search: "Buscar partidos",
    searching: "Buscando…",
    start: "Elegí una fecha, liga o equipo y buscá partidos.",
    empty: "No se encontraron partidos para esa búsqueda.",
    hint: "Con la API free, la búsqueda por equipo suele funcionar mejor con “Arsenal”. Fecha y liga funcionan bien.",
    errors: {
      needFilter: "Elegí al menos una fecha, una liga o un equipo.",
      fetch: "No se pudieron cargar los partidos. Intentá de nuevo.",
    },
  },
} as const;
