export const appContent = {
  appName: "Camino",
  tagline: "Planificá tu día, tu semana y tus objetivos",
  nav: {
    dashboard: "Hoy",
    weekly: "Semana",
    monthlyGoals: "Objetivos mensuales",
    annualGoals: "Objetivos anuales",
    football: "Fútbol",
    statistics: "Estadísticas",
    calendar: "Calendario",
  },
  auth: {
    loginTitle: "Iniciar sesión",
    registerTitle: "Crear cuenta",
    email: "Correo electrónico",
    password: "Contraseña",
    name: "Nombre",
    loginButton: "Ingresar",
    registerButton: "Registrarse",
    googleButton: "Continuar con Google",
    noAccount: "¿No tenés cuenta?",
    hasAccount: "¿Ya tenés cuenta?",
    registerLink: "Registrate",
    loginLink: "Iniciá sesión",
    logout: "Cerrar sesión",
    errors: {
      invalidCredentials: "Correo o contraseña incorrectos",
      emailInUse: "Este correo ya está registrado",
      googleConflict: "Este correo ya tiene cuenta con contraseña. Iniciá sesión con email.",
      dbUnavailable: "No se pudo conectar a la base de datos. Revisá tu conexión o la configuración de Atlas.",
      generic: "Ocurrió un error. Intentá de nuevo.",
    },
  },
  dashboard: {
    title: "Agenda de hoy",
    subtitle: "Tareas organizadas por bloque horario",
    emptySlot: "Escribí una tarea…",
    addTask: "Agregar tarea",
    editTask: "Editar tarea",
    markComplete: "Completar",
    markIncomplete: "Marcar pendiente",
    deleteTask: "Eliminar",
    taskTitle: "Tarea",
    save: "Guardar",
    cancel: "Cancelar",
    completed: "Completada",
    pending: "Pendiente",
    todayMatchesTitle: "Partidos de hoy",
    todayMatchesMore: "Ver más",
    todayMatchesEmpty: "No hay partidos para hoy.",
    todayMatchesError: "No se pudieron cargar los partidos.",
    notes: {
      title: "Notas del día",
      placeholder: "Escribí lo que quieras recordar de hoy…",
      showPanel: "Mostrar notas",
      openModal: "Abrir notas del día",
      closePanel: "Cerrar panel de notas",
      resizePanel: "Redimensionar panel de notas",
    },
  },
  weekly: {
    title: "Planificación semanal",
    subtitle: "Agenda y objetivos de la semana",
    agendaTitle: "Agenda semanal",
    goalsTitle: "Objetivos semanales",
    prevWeek: "Semana anterior",
    nextWeek: "Semana siguiente",
    addGoal: "Nuevo objetivo",
    goalPlaceholder: "Escribí un objetivo para esta semana",
  },
  monthlyGoals: {
    title: "Objetivos mensuales",
    subtitle: "Metas del mes en curso",
    addGoal: "Nuevo objetivo",
    goalPlaceholder: "Objetivo del mes",
    prevMonth: "Mes anterior",
    nextMonth: "Mes siguiente",
  },
  annualGoals: {
    title: "Objetivos anuales",
    subtitle: "Metas del año",
    addGoal: "Nuevo objetivo",
    goalPlaceholder: "Objetivo del año",
    prevYear: "Año anterior",
    nextYear: "Año siguiente",
  },
  goals: {
    markComplete: "Completar",
    markIncomplete: "Marcar pendiente",
    edit: "Editar",
    delete: "Eliminar",
    empty: "No hay objetivos todavía",
    save: "Guardar",
    cancel: "Cancelar",
  },
  assistant: {
    title: "Asistente de Camino",
    open: "Abrir asistente",
    close: "Cerrar asistente",
    placeholder: "Ej. Creame una tarea hoy a las 16…",
    send: "Enviar",
    thinking: "Pensando…",
    working: "Actualizando tu agenda…",
    greeting:
      "¡Hola! Puedo explicarte Camino o ayudarte a usarla: por ejemplo, pedime crear una tarea para hoy a una hora.",
    error: "No se pudo responder. Intentá de nuevo.",
  },
  football: {
    title: "Fútbol",
    subtitle: "Buscá partidos por fecha, liga o equipo",
    date: "Fecha",
    league: "Liga",
    anyLeague: "Todas las ligas",
    team: "Equipo",
    teamPlaceholder: "Ej. Arsenal",
    clearTeam: "Quitar",
    scope: "Para liga/equipo",
    scopeNext: "Próximos",
    scopeLast: "Últimos",
    search: "Buscar partidos",
    searching: "Buscando…",
    clearSearch: "Limpiar búsqueda",
    start: "Elegí una fecha, liga o equipo y buscá partidos.",
    empty: "No se encontraron partidos para esa búsqueda.",
    addToAgenda: "Agregar a la agenda",
    addToAgendaShort: "Agregar",
    addedToAgenda: "En agenda",
    outOfWeek: "Fuera de esta semana",
    errors: {
      needFilter: "Elegí al menos una fecha, una liga o un equipo.",
      fetch: "No se pudieron cargar los partidos. Intentá de nuevo.",
      outOfWeek: "Solo se pueden agregar partidos de la semana actual.",
      slotOccupied: "Ese horario ya tiene una tarea en la agenda.",
      addFailed: "No se pudo agregar el partido. Intentá de nuevo.",
    },
  },
  stats: {
    title: "Estadísticas",
    subtitle: "Resumen de tu progreso en tareas y objetivos",
    goalsHint: "Semana actual, mes actual y año en curso",
    dragChart: "Arrastrar gráfico",
    resizeChart: "Redimensionar alto del gráfico",
    resizeChartWidth: "Redimensionar ancho del gráfico",
    expandChart: "Ver gráfico en grande",
    openChart: "Ver gráfico",
    closeExpandedChart: "Cerrar vista ampliada",
    charts: {
      completedPerDay: "Tareas completadas por día",
      tasksStacked: "Completadas vs pendientes por día",
      completionMix: "Balance del mes",
      goalsProgress: "Objetivos completados",
    },
  },
  calendar: {
    title: "Calendario",
    subtitle: "Revisá tareas y notas de cualquier día del año",
    prevYear: "Año anterior",
    nextYear: "Año siguiente",
    dayDetailTitle: "Detalle del día",
    noTasks: "No hay tareas con texto en este día.",
    noteTitle: "Nota del día",
    noNote: "No hay nota guardada para este día.",
    statsTotal: "Tareas",
    statsCompleted: "Completadas",
    statsPending: "Pendientes",
    slotLabel: "Bloque",
    completedAtLabel: "Completada a las",
    completedAtUnknown: "Sin hora registrada (marcada antes de esta función)",
    completedSection: "Completadas",
    pendingSection: "Pendientes",
    legendTasks: "Con tareas",
    legendNote: "Con nota",
    legendToday: "Hoy",
    closeDayDetail: "Cerrar detalle del día",
  },
  desktop: {
    downloadButton: "Descargar app",
    downloadAria: "Descargar Camino para escritorio (Windows)",
    downloadHint: "Instalador de escritorio para Windows",
    downloadUnavailable:
      "La descarga de escritorio se publica en GitHub Releases (configurá NEXT_PUBLIC_DESKTOP_DOWNLOAD_URL).",
  },
} as const;
